### ISSUE TITLE
Floating point path data

### ISSUE THREAD

**Issue by ghost** [dy/svg-path-bounds#1]
Does your program work only with integer data? When trying to test a path with floating points i get this in the node repl:

> getBounds("M404 10v173h28v-366h-28v162c-5.33301 -36.667 -30 -64.333 -74 -83c-37.333 -16 -81.333 -23.667 -132 -23c-48.667 0.666992 -91 9.66699 -127 27c-42 19.333 -65.667 46.667 -71 82v-165h-28v366h28v-173c5.33301 38.667 28.333 68.667 69 90c36 18 79 27 129 27
getBounds("M404 10v173h28v-366h-28v162c-5.33301 -36.667 -30 -64.333 -74 -83c-37.333 -16 -81.333 -23.667 -132 -23c-48.667 0.666992 -91 9.66699 -127 27c-42 19.333 -65.667 46.667 -71 82v-165h-28v366h28v-173c5.33301 38.667 28.333 68.667 69 90c36 18 79 27 129 27
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token

> s94.333 -9.66699 133 -29c43.333 -21.333 67.667 -50.667 73 -88zM-112 -183v366h28v-366h-28zM489 -183v366h29v-366h-29zM242 -108c34.667 10.667 52 38.667 52 84c0 32.667 -10 62.667 -30 90c-22 30 -48.667 45 -80 45c-6.66699 0 -13.667 -1 -21 -3
s94.333 -9.66699 133 -29c43.333 -21.333 67.667 -50.667 73 -88zM-112 -183v366h28v-366h-28zM489 -183v366h29v-366h-29zM242 -108c34.667 10.667 52 38.667 52 84c0 32.667 -10 62.667 -30 90c-22 30 -48.667 45 -80 45c-6.66699 0 -13.667 -1 -21 -3
   ^^^^

SyntaxError: Unexpected number

> c-32 -8 -48 -35 -48 -81c0 -34.667 8 -65.333 24 -92c19.333 -31.333 45.333 -47 78 -47c8 0 16.333 1.33301 25 4z"

**Comment by dy** [comment]
It works with floats too: https://github.com/dy/svg-path-bounds/blob/master/test.js#L14.
Can you show input data?

**Comment by ghost** [comment]
I found the problem, the input data containes newline and white spaces. Now it works
